---
title: "data_cleanup"
author: "Dylan Reher & Patrick Murphy"
date: "2025-10-13"
output: html_document
---

```{r}
library(readr)
melanoma_data_cleaned <- read.csv("melanoma_data_cleaned.csv")
View(melanoma_data_cleaned)
colnames(melanoma_data_cleaned)[1] <- "county_melanoma"
colnames(melanoma_data_cleaned)[2] <- "fips_melanoma"
colnames(melanoma_data_cleaned)[3] <- "county_type"
colnames(melanoma_data_cleaned)[4] <- "age_adj_inc_rate"
melanoma_data_cleaned <- melanoma_data_cleaned[-1, ] 
melanoma_data_cleaned <- melanoma_data_cleaned[, -c(7, 8, 9)]
colnames(melanoma_data_cleaned)[5] <- "lower_95_conf"
colnames(melanoma_data_cleaned)[6] <- "upper_95_conf"
colnames(melanoma_data_cleaned)[7] <- "avg_annual_ct"
colnames(melanoma_data_cleaned)[8] <- "recent_trend"
colnames(melanoma_data_cleaned)[9] <- "recent_five_yr_trend"
colnames(melanoma_data_cleaned)[10] <- "lower_95_ci"
colnames(melanoma_data_cleaned)[11] <- "upper_95_ci"

#separate the county and state
library(stringr)

split <- str_split(melanoma_data_cleaned[[1]],", ")
counties <-sapply (split,
                   function(x) {x[1]})

states <-sapply (split,
                   function(x) {x[2]})

#in code below may want to delete city and census area 

# might edit out code below because honestly making more issues
#counties <- str_remove(counties, "\\s+(County|Parish|City|Borough|Census Area)$")

melanoma_data_cleaned$county <- counties
melanoma_data_cleaned$state  <- states


#clean up the 6/7 values at the end of the states column
#Need to look at district of Colombia and where to put that 

melanoma_data_cleaned$state <- gsub("\\s*\\((6|7)\\)\\s*", " ", melanoma_data_cleaned$state)

melanoma_data_cleaned$avg_annual_ct[melanoma_data_cleaned$avg_annual_ct == "data not available"] <- NA
melanoma_data_cleaned$avg_annual_ct[melanoma_data_cleaned$avg_annual_ct == "3 or fewer"] <- 0

#below is code that changes the column from character to numeric/vector column (auto character as we have text in there)

melanoma_data_cleaned$avg_annual_ct <-as.numeric(melanoma_data_cleaned$avg_annual_ct)

#Bedford GeoID wrong 
melanoma_data_cleaned[723,2] <-"51019"

#number avg annual count/population in the county 
    
#Code below removes all rows with Alaska because it is not found in uv_county so want to remove for now 

drop_idx <- grepl("^\\s*(alaska|ak)\\s*$", melanoma_data_cleaned$state, ignore.case = TRUE)
melanoma_data_cleaned <- melanoma_data_cleaned[!drop_idx, , drop = FALSE]



write.csv(melanoma_data_cleaned, "cleaned_melanoma_table.csv")



```

```{r}
library(readxl)
uv_county <- read_excel("uv-county.xlsx")
View(uv_county)
colnames(uv_county)[1] <- "state_uv"
colnames(uv_county)[2] <- "state_abr"
colnames(uv_county)[3] <- "fips_uv"
colnames(uv_county)[4] <- "county_name"
colnames(uv_county)[5] <- "uv_whm2"

write.csv(uv_county, "cleaned_uv_table.csv", row.names = FALSE)

#lacks county and city name. Essentially need to add to each state by state
#Match by state and first word of county for leaflet!!!
```


```{r}
library(readr)
county_demographics <- read.csv("county_demographics.csv")
View(county_demographics)
colnames(county_demographics)[1] <- "county_demo"
colnames(county_demographics)[2] <- "state_abr_demo"
colnames(county_demographics)[3] <- "age_pct_over_65"
colnames(county_demographics)[4] <- "age_pct_under_18"
colnames(county_demographics)[5] <- "age_pct_under_5"
colnames(county_demographics)[6] <- "american_indian_alaska_native_pct"
colnames(county_demographics)[7] <- "asian_pct"
colnames(county_demographics)[8] <- "black_pct"
colnames(county_demographics)[9] <- "hispanic_or_latino_pct"
colnames(county_demographics)[10] <- "hawaiian_pacific_islander_pct"
colnames(county_demographics)[11] <- "two_more_races"
colnames(county_demographics)[12] <- "white_pct"
colnames(county_demographics)[13] <- "white_not_h_or_l_pct"
library(stringr)
#code below removes county and other things after except city (maybe keep census area also) 
#county_demographics$county_demo <- str_remove(county_demographics$county_demo, "\\s+(County|Parish|Borough|Census Area)$")

#Code below removes all rows with Alaska because it is not found in uv_county so want to remove for now 
rm_idx <- toupper(county_demographics$state_abr_demo) %in% c("AK", "ALASKA")
county_demographics <- county_demographics[!rm_idx, , drop = FALSE]

drop_idx <- grepl("^\\s*(alaska|ak)\\s*$", county_demographics$state_abr_demo, ignore.case = TRUE)
county_demographics <- county_demographics[!drop_idx, , drop = FALSE]


```

```{r}
#Is dataset below just 2020-2024 or 2019-2024??
library(readxl)
county_population <- read_excel("co-est2024-pop (1).xlsx")
View(county_population)
colnames(county_population)[1] <- "county_state_pop"
#removes period in front of each row on column 1 
library(stringr)
county_population$county_state_pop <-str_remove(county_population$county_state_pop, "^\\.+\\s*")



#code below makes new columns called county and state and removes word county and more
split <- str_split(county_population[[1]],", ")
counties <-sapply (split,
                   function(x) {x[1]})

states <-sapply (split,
                   function(x) {x[2]})

#counties <- str_remove(counties, "\\s+(County|Parish|City|Borough|Census Area)$")

county_population$county <- counties
county_population$state  <- states


#deletes all of row 1
county_population<- county_population[-1,]

#need to figure out and rename column 2

#Code below removes all rows with Alaska because it is not found in uv_county so want to remove for now 
drop_idx <- grepl("^\\s*(alaska|ak)\\s*$", county_population$state, ignore.case = TRUE)
county_population <- county_population[!drop_idx, , drop = FALSE]

#Code below removes row that is no data and useless
target <- "Annual Estimates of the Resident Population for Counties in the United States: April 1, 2020 to July 1, 2024 (CO-EST2024-POP)"
idx <- which(trimws(county_population$county_state_pop) == target)
county_population <- county_population[-idx, , drop = FALSE]
row.names(county_population) <- NULL

```



